#!/bin/bash
set -ex

# Create archive
qmake CONFIG+=release .
make dist
make distclean

# Give it a debian name
rename "s/trabucco/trabucco_/" *.tar.gz
rename "s/.tar.gz/.orig.tar.gz/" *.tar.gz

ARCHIVE=$(ls *.orig.tar.gz)

# Remove Qt crap from the archive
TMPDIR=$(mktemp -d)
mv $ARCHIVE $TMPDIR
pushd $TMPDIR
tar -xf *
rm -rf $(find | grep /usr)
rm $ARCHIVE
tar -czf $ARCHIVE *
popd
mv $TMPDIR/$ARCHIVE .
rm -rf "$TMPDIR"

# Sign the archive
gpg --sign --armor --detach-sign *.orig.tar.gz



T=$(mktemp -d)
mv *orig.tar.gz* $T
cp -r debian $T

pushd $T
tar -xf *gz
CODEDIR=$(find .  -maxdepth 1 -type d | egrep -v debian\|\\.$)
mv debian $CODEDIR

pushd $CODEDIR
dpkg-buildpackage --changes-option=-S
popd

rm -rf "$CODEDIR"

popd
mkdir deb-pkg
mv $T/* deb-pkg
rmdir $T
lintian --pedantic -E --color auto -i -I deb-pkg/*changes
