.TH "ynew" "1" 
.SH "NAME" 
ynew \(em yakuake tab launcher.
.SH "SYNOPSIS" 
.PP 
\fBynew\fR COMMAND
.SH "DESCRIPTION" 
.PP 
ynew launches a new tab in yakuake, setting a name for it.
.br
For example, we can ssh into a server called "alfio" and have the session into a yakuake tab named "alfio". Or we can have "top" running in a tab named "top".
.br
When calling ynew with a command name that doesn't exist yet, an editor is opened to write the script. For example "exec ssh alfio".
.b
The successive times a new yakuake tab is created and the command is executed into that tab.
.SH "Files"
Commands are stored under $HOME/.ynew
